import type { Cli } from '@lockness/cli'
import { generateOpenAPISpec } from './generator.ts'
import type { ControllerClass } from '@lockness/contract'
import { join } from '@std/path'

export function registerOpenAPICommands(cli: Cli) {
    cli.register(
        'docs:generate',
        async (args: string[]) => {
            console.log('📝 Generating OpenAPI specification...\n')

            // Parse options
            const options = parseOptions(args)

            // Get all controllers
            const controllers: ControllerClass[] = []

            // Scan app/controller directory
            const controllersDir = './app/controller'
            try {
                for await (const entry of Deno.readDir(controllersDir)) {
                    if (
                        entry.isFile &&
                        (entry.name.endsWith('_controller.ts') ||
                            entry.name.endsWith('_controller.tsx'))
                    ) {
                        const modulePath = join(controllersDir, entry.name)
                        const module = await import(
                            `file://${Deno.cwd()}/${modulePath}`
                        )

                        // Get all exported controllers
                        for (const key of Object.keys(module)) {
                            const exported = module[key]
                            if (
                                typeof exported === 'function' &&
                                key.endsWith('Controller')
                            ) {
                                controllers.push(exported as ControllerClass)
                            }
                        }
                    }
                }
            } catch (error) {
                console.error('❌ Error scanning controllers:', error)
                return
            }

            // Generate spec
            const spec = generateOpenAPISpec(controllers, {
                title: options.title || 'Lockness API',
                version: options.version || '1.0.0',
                description:
                    'API documentation generated by Lockness OpenAPI generator',
            })

            // Write to file
            const outputPath = options.output || 'public/openapi.json'
            await Deno.writeTextFile(
                outputPath,
                JSON.stringify(spec, null, 2),
            )

            console.log(`✅ OpenAPI spec generated at: ${outputPath}`)
            console.log(
                `   Found ${
                    Object.keys(spec.paths).length
                } documented endpoints`,
            )
            console.log(`   ${spec.tags?.length || 0} tags`)
            console.log(`\n💡 View docs at: http://localhost:8888/api-docs`)
        },
        'Generate OpenAPI specification from controllers',
    )
}

function parseOptions(args: string[]): {
    output?: string
    title?: string
    version?: string
} {
    const options: { output?: string; title?: string; version?: string } = {}

    for (let i = 0; i < args.length; i++) {
        const arg = args[i]
        if (arg === '--output' || arg === '-o') {
            options.output = args[++i]
        } else if (arg === '--title' || arg === '-t') {
            options.title = args[++i]
        } else if (arg === '--version' || arg === '-v') {
            options.version = args[++i]
        }
    }

    return options
}
